import turtle 

star = turtle.Turtle()
for x in range(50):
    star.pencolor("red")
    star.forward(200)
    star.right(135)
    star.pencolor("Yellow")
    star.forward(200)
    star.right(135)
    star.pencolor("orange")
    star.forward(200)
    star.right(135)
    star.pencolor("blue")
    star.forward(200)
    star.right(135)
    star.pencolor("violet")
    star.forward(200)
    star.right(135)
    star.pencolor("green")
    star.forward(200)
    star.right(135)
    star.pencolor("cyan")
    star.forward(200)
    star.right(135)
    star.pencolor("magenta")
    star.forward(200)
    star.right(135)
