import turtle
 
myTurtle = turtle.Turtle()

def circles(velocity,size ):
    myTurtle.speed(velocity)
    myTurtle.circle(size)
    
myTurtle.pencolor("red") 
circles(1,100)
myTurtle.pencolor("blue") 
circles(2,100)
myTurtle.pencolor("green") 
circles(3,100)
myTurtle.pencolor("yellow") 
circles(4,100)
myTurtle.pencolor("cyan")
circles(5,100)
myTurtle.pencolor("magenta") 
circles(6,100)
myTurtle.pencolor("cyan") 
circles(7,100)
myTurtle.pencolor("pink") 
circles(8,100)
myTurtle.pencolor("brown") 
circles(9,100)
myTurtle.pencolor("orange") 
circles(10,100)
myTurtle.pencolor("black") 
circles(11,100)
#turtle.getscreen()._root.mainloop()
